#  POSTGRES CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/productos
spring.datasource.username=postgres
spring.datasource.password=admin1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ==============================
# CONFIGURACIÓN H2 (DESACTIVADA)
# ==============================

# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# spring.datasource.url=jdbc:h2:file:./data/productosdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# logging.level.org.hibernate.SQL=DEBUG




